### ISSUE TITLE
WSL: Not supported?

### ISSUE THREAD

**Issue by MartinThoma** [flyingcircusio/vulnix#66]
Is WSL (Windows subsystem for Linux) not supported?

I get

```
$ vulnix --system
CRITICAL:vulnix.main:path `/nix/var/nix/gcroots/current-system` does not exist - cannot load derivations referenced from it
```

**Comment by ckauhaus** [comment]
Hi Martin, thanks for the report. This is probably because nobody has tried this before. `vulnix --system` is targeted specifically at hosts running NixOS. I suppose that WSL is more like nixpkgs used on top of a different host distro. Did you install individual packages via `nix-env` or is there a `/etc/nixos/configuration.nix` in use?

**Comment by MartinThoma** [comment]
> Did you install individual packages via nix-env or is there a /etc/nixos/configuration.nix in use?

I'm sorry, I don't know. I install packages with apt or pip. Does that answer the question?

I was looking for a tool that can check requirementst.txt files for vulnerabilities in the pinned Python packages. I realized that vulnix is not the right tool for that but was curious what it would give me.

**Comment by ckauhaus** [comment]
vulnix is a tool specifically targeted at NixOS / nixpkgs. Alhough it is written in Python, it has no functionality for checking stand alone Python projects.

If you are active on GitHub: They offer to scan your repo for problematic dependencies.

You may also check out:
* https://github.com/pyupio/pyup
* https://pypi.org/project/poetry/
